### ISSUE TITLE
fusion-cli introduces regressions to how commonJS modules are compiled

### ISSUE THREAD

**Issue by vicapow** [fusionjs/fusion-cli#632] opened 2018-11-28 17:27 UTC
newer versions of fusion expect all node_module dependencies to support 'use_strict` which would be a breaking change. I'll be adding more detail here but creating the ticket now to track internally.

**Comment by vicapow** [comment] 2018-11-28 17:47
likely the same as https://github.com/fusionjs/fusion-cli/issues/622

**Comment by rtsao** [comment] 2018-11-28 21:03
Duplicate of https://github.com/fusionjs/fusion-cli/issues/627

**Closed by rtsao** 2018-11-28 21:03 UTC
