### ISSUE TITLE
AssetUrl not appending `/_static/` on client side

### ISSUE THREAD

**Issue by rasmusprentow** [fusionjs/fusion-cli#398] opened 2018-06-20 12:40 UTC
### Type of issue

Bug

### Description

When using `assetUrl` the path is resolved correctly when run on server side, but when used on client side it does not work. 
This results in assets not being loaded properly when using helmet. 
This was not a problem without helmet since we used middleware to append html to the index file. 
The problem is as far as I can tell not a problem with Helmet, but a problem with the transformation of the URL made by the build step. 

I have only tested this with `fusion dev` and not with a production build.

### Current behavior

Rendering on client side produces assets url without `/_static/` prefix
Rendering on server side produces assets url prefixed with `/_static/` 

### Expected behavior

The same url should be produced on both client and server. 

### Steps to reproduce

1. Create new app
2. Make root component: 
```
// @flow
import React from 'react';
import {assetUrl} from 'fusion-core';
import {Helmet} from 'fusion-plugin-react-helmet-async';
import {Route, Switch} from 'fusion-plugin-react-router';
import Welcome from './welcome.js';

const faviconPath = assetUrl('../static/favicon.ico');

export const Root = () => (
  <div id="wrapper">
    <Helmet>
      <link rel="shortcut icon" type="image/x-icon" href={faviconPath} />
      <link rel="icon" type="image/x-icon" href={faviconPath} />
    </Helmet>
    <Switch>
      <Route exact path="/" component={Welcome} />
    </Switch>
  </div>
);
export default <Root />;
```

Page will then work fine on first render where the server side generated page is loaded, but once JS starts running the favicon will disappear. 

Modifying the above code like this will make it work. 
```
-const faviconPath = assetUrl('../static/favicon.ico');
+const faviconPath = (__BROWSER__ ?  '/_static/' : '') + assetUrl('../static/favicon.ico');
```

### Your environment

* fusion-cli version: 1.7.0

* Node.js version (`node --version`): 8.11.3

* npm version (`npm --version`): 5.6.0

* Operating System: MacOS

**Comment by KevinGrandon** [comment] 2018-06-21 23:16
Was unable to reproduce this issue, but I will keep investigating. What version of fusion-core are you using?

**Comment by KevinGrandon** [comment] 2018-07-04 06:45
Fixed in: https://github.com/fusionjs/fusion-cli/pull/414

**Closed by KevinGrandon** 2018-07-04 06:45 UTC
