### ISSUE TITLE
Remove node-zopfli replace with zlib

### ISSUE THREAD

**Issue by vicapow** [fusionjs/fusion-cli#416] opened 2018-07-03 03:49 UTC
node-zopfli is an old, native module that was last updated in 2016. It adds a lot of time to the installation and is error prone. Should be replaced with zlib builtin module: https://nodejs.org/api/zlib.html

**Comment by rtsao** [comment] 2018-07-03 04:57
Duplicate of https://github.com/fusionjs/fusion-cli/issues/111

**Closed by rtsao** 2018-07-03 04:57 UTC
