### ISSUE TITLE
Fusion 1.13.0-beta.14 not showing source-maps with NODE_ENV=production

### ISSUE THREAD

**Issue by vicapow** [fusionjs/fusion-cli#629] opened 2018-11-28 02:28 UTC
The files exist in `_static` but chrome isn't loading them. I believe this is because the `//# sourceURL= ...`  directive isn't being added to the minified code.

**Comment by rtsao** [comment] 2018-11-28 21:04
Duplicate of https://github.com/fusionjs/fusion-cli/issues/626

**Closed by rtsao** 2018-11-28 21:04 UTC
