### ISSUE TITLE
How to make a "serverless" fusion app with the stripping of node.js?

### ISSUE THREAD

**Issue by wheelo** [fusionjs/fusion-cli#585] opened 2018-10-23 08:11 UTC
### Type of issue
Feature request

### Description
I find that the current version of fusion.js is merely made for React SSR app, that I can only access the entry point by some hidden logic under fusion-cli's entry file. As u illustrated in code of  [L29](https://github.com/fusionjs/fusion-cli/blob/master/entries/client-entry.js#L29) it is designed for some FUSION_ENTRY_PATH entry, which is also used by node hot server.
Here, I got one situation that only require the bundled React logic(for some jssdk). Is that possible to integrate the **fusion** independent of fusion-cli? That is  

### Current behavior
 ```javascript
import App from 'fusion-react';
import Router from 'fusion-plugin-react-router';

const app = new App(root);
app.register(Router);
// I add this line: https://github.com/fusionjs/fusion-cli/blob/master/entries/client-entry.js#L29
app.callback().call();
```

### Expected behavior
```javascript
 // Could I shorten the calling process to this in my sdk?
 const app = new App(root);
 app.register(Router);
```

**Comment by KevinGrandon** [comment] 2018-10-23 19:31
Thank you for filing a bug report. I think this is possible today, but also quite hacky. You can construct a HTML file and pull in the .fusion/ generated scripts manually. I think we would need to do a lot of work to fully support applications without a server, but it could be possible with time.

Curious about your usecase, why don't you want to use a server?

**Comment by wheelo** [comment] 2018-10-24 01:51
@KevinGrandon Currently, the server api is provided solely by some Java server, and we put the static javascript file and some HTMLs in nginx static server

**Comment by mlmorg** [comment] 2019-05-03 20:09
Going to close this as a duplicate of https://github.com/fusionjs/fusion-cli/issues/484.

**Closed by mlmorg** 2019-05-03 20:09 UTC
