### ISSUE TITLE
Run example in windows

### ISSUE THREAD

**Issue by tcper** [fusionjs/fusion-cli#485] opened 2018-08-27 03:44 UTC
I've run the first app in windows, but generated 
.fusion/dist/development/server/server-main.js
path always wrong.

`require('C:\Users\may\code\my-fusion-app\node_modules\source-map-support\source-map-support.js').install();
`

all backslash are lost.
so, I added

`let sourceMapPath = require.resolve('source-map-support');
sourceMapPath = sourceMapPath.replace(/\\/g, '\\\\');`

in build/compiler.js to solve this problem.
but don't know maybe some side effect, hope you guys solve this officially.

**Comment by KevinGrandon** [comment] 2018-08-27 05:57
Thanks for filing the issue and sorry about the problem. I'm going to mark this as a duplicate of: https://github.com/fusionjs/fusion-cli/issues/461#issuecomment-411294134

We are currently recommending that folks use Docker on windows. Here are the steps to do so:

* Clone or download this folder: https://github.com/KevinGrandon/fusion-boilerplate/tree/master/docker-fusion-app
* Run: docker-compose up

**Closed by KevinGrandon** 2018-08-27 05:57 UTC
